name: Cronjob operations

on:
  #schedule:
  #  - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  pocket-to-linkding:
    runs-on: ubuntu-latest
    container: ghcr.io/juev/rss-parser:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: 🚀 Run Automation
        run: bash ./scripts/getpocket.sh
        env:
          LINKDING_TOKEN: ${{ secrets.LINKDING_TOKEN }}
      - name: 🚀 Print
        run: echo 'Hello World!'
