name: Cronjob operations

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minuts
  workflow_dispatch:

jobs:
  pocket-to-linkding:
    runs-on: ubuntu-latest
    container: ghcr.io/juev/tools:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 🚀 Run Automation
        run: bash ./scripts/getpocket.sh
        env:
          LINKDING_TOKEN: ${{ secrets.LINKDING_TOKEN }}
